#!/usr/bin/env python3
"""
train_yolo.py
──────────────
Phase 2: Fine-tune YOLOv8n on the annotated painting dataset.

Prerequisites:
  1. Run annotate_helper.py to generate pre-annotations
  2. Review and correct labels using CVAT, Label Studio, or LabelImg
  3. Ensure data.yaml points to the correct dataset paths

This script:
  - Uses YOLOv8n (nano, ~6 MB) for maximum CPU inference speed
  - Freezes the backbone (first 10 layers) to prevent overfitting on small datasets
  - Enables aggressive augmentation (mosaic, rotation, scaling)
  - Uses early stopping (patience=20) to prevent over-training
  - Saves the best model to models/best.pt

Usage:
  python train_yolo.py --data dataset/data.yaml
  python train_yolo.py --data dataset/data.yaml --epochs 200 --imgsz 640
  python train_yolo.py --data dataset/data.yaml --device cpu
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))


def main():
    parser = argparse.ArgumentParser(
        description="Fine-tune YOLOv8n for painting detection (Phase 2).",
    )
    parser.add_argument(
        "--data",
        required=True,
        help="Path to data.yaml (generated by annotate_helper.py).",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=100,
        help="Maximum training epochs (default: 100).",
    )
    parser.add_argument(
        "--imgsz",
        type=int,
        default=640,
        help="Training image size (default: 640).",
    )
    parser.add_argument(
        "--batch",
        type=int,
        default=4,
        help="Batch size (default: 4 for CPU training).",
    )
    parser.add_argument(
        "--device",
        default="cpu",
        help="Training device (default: cpu).",
    )
    parser.add_argument(
        "--freeze",
        type=int,
        default=10,
        help="Number of backbone layers to freeze (default: 10).",
    )
    parser.add_argument(
        "--patience",
        type=int,
        default=20,
        help="Early stopping patience (default: 20 epochs).",
    )
    parser.add_argument(
        "--output",
        default="models",
        help="Output directory for trained weights (default: 'models/').",
    )
    parser.add_argument(
        "--base-model",
        default="yolov8n.pt",
        help="Base model weights for transfer learning (default: yolov8n.pt).",
    )

    args = parser.parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    from ultralytics import YOLO

    print("=" * 60)
    print("  YOLO Painting Detector — Phase 2 Training")
    print("=" * 60)
    print(f"  Base model:  {args.base_model}")
    print(f"  Dataset:     {args.data}")
    print(f"  Epochs:      {args.epochs}")
    print(f"  Image size:  {args.imgsz}")
    print(f"  Batch size:  {args.batch}")
    print(f"  Device:      {args.device}")
    print(f"  Freeze:      {args.freeze} layers")
    print(f"  Patience:    {args.patience}")
    print(f"  Output:      {output_dir}")
    print("=" * 60)
    print()

    # Load pretrained model
    model = YOLO(args.base_model)

    # Train
    results = model.train(
        data=args.data,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        freeze=args.freeze,
        patience=args.patience,
        augment=True,
        # Save best model
        save=True,
        save_period=-1,  # only save best + last
        # Project settings
        project=str(output_dir),
        name="painting_detector",
        exist_ok=True,
        # Augmentation settings optimised for paintings
        degrees=15.0,       # rotation (paintings can be slightly angled)
        translate=0.1,      # translation
        scale=0.5,          # scale variance (paintings at various distances)
        fliplr=0.5,         # horizontal flip
        flipud=0.0,         # no vertical flip (paintings are upright)
        mosaic=1.0,         # mosaic augmentation
        mixup=0.1,          # light mixup
        # Verbose
        verbose=True,
    )

    # Copy best weights to output directory
    best_path = output_dir / "painting_detector" / "weights" / "best.pt"
    if best_path.exists():
        import shutil
        final_path = output_dir / "best.pt"
        shutil.copy2(str(best_path), str(final_path))
        print(f"\n✓ Best model saved to: {final_path}")
        print(f"\nTo use this model:")
        print(f"  python yolo_artwork_cropper.py painting.jpg --model {final_path}")
        print(f"  python yolo_artwork_cropper.py ./images/ --batch --model {final_path}")
    else:
        print(f"\n⚠️  Training completed but best.pt not found at expected path.")
        print(f"  Check {output_dir / 'painting_detector'} for results.")


if __name__ == "__main__":
    main()
